Repository jenaye/Tipnturn-front, pull requests merged in 2018-07, with the labels that each got.

#52 Add listing of activities and update menu
  README.md
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/all-activities/all-activities.component.css
  src/app/components/all-activities/all-activities.component.html
  src/app/components/all-activities/all-activities.component.ts
  src/app/components/all-events/all-event.component.css
  src/app/components/side-bar/side-bar.component.html
Labels: Work in progress, enhancement

#53 [Feat] add possibility to download members as csv
  src/app/components/all-members/all-members.component.html
  src/app/components/all-members/all-members.component.ts
  src/app/components/financial/financial.component.ts
  src/app/services/csv.service.ts
Labels: Ready to review, enhancement

#54 Create PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: Done

#56 Feature/members fix
  dist.zip
  src/app/components/addMember/addMember.component.html
  src/app/components/addMember/addMember.component.ts
  src/app/components/all-members/all-members.component.html
  src/app/components/all-members/all-members.component.ts
  src/app/components/editmember/editmember.component.html
  src/app/components/editmember/editmember.component.ts
  src/app/services/members.service.ts
  src/environments/environment.ts
Labels: Ready to review, bug

#57 Feature/chart colors
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: Ready to review, enhancement

#59 Readme/update
  README.md
Labels: Ready to review
